### ISSUE TITLE
Allow to customize FPS

### ISSUE THREAD

**Issue by joaomoreno** [joaomoreno/gifcap#1]

**Comment by procload** [comment]
Does this mean you can control how fast things play back? I'd like the gifs to play back in real time if possible. I primarily would use this for screen recording of UI patterns, but the ultra fast playback makes that impossible.

**Comment by joaomoreno** [comment]
I saw someone else mention that their gifs were not running at real time: https://news.ycombinator.com/item?id=22733912

@procload Is this true for you? The GIFs should always run at real time, it's an issue if they don't. Are they too fast? Are they too slow? The preview should actually already show whether it's too fast/slow.

**Comment by timmayvaian** [comment]
> I saw someone else mention that their gifs were not running at real time: https://news.ycombinator.com/item?id=22733912
> 
> @procload Is this true for you? The GIFs should always run at real time, it's an issue if they don't. Are they too fast? Are they too slow? The preview should actually already show whether it's too fast/slow.

To add to this, yesterday the timing was real time, but today its way too fast, both times with Chrome. Tried with several browsers, it actually wont even load with Edge/Explorer.

Thanks man, so much hilarity with come from this tool. 
![6e54ab5b-a7a8-45c3-9836-a7d4d5a46199](https://user-images.githubusercontent.com/32347634/78384378-107ffc00-75a8-11ea-8970-4de18b726330.gif)

**Comment by joaomoreno** [comment]
@procload See #19

**Comment by joaomoreno** [comment]
Closing as won't happen
