### ISSUE TITLE
Start recording with a 3 second timeout

### ISSUE THREAD

**Issue by isidorn** [joaomoreno/gifcap#11]
I don't want my every gif to start with a recording of your home page.
Recording should be started with a 3 second timeout.

**Comment by joaomoreno** [comment]
@isidorn Have you tried trimming your recording? https://twitter.com/i/status/1243826344389214208

**Comment by isidorn** [comment]
@joaomoreno no, but that means I have to trim every recording I do. I can try it out.
Lifecap does a 3 second timeout before starging to record so users might be used to this like me.

**Comment by joaomoreno** [comment]
> @joaomoreno no, but that means I have to trim every recording I do. I can try it out.

There are two possible annoyances:

- Trim every recording
- Wait 3 seconds before every recording

I really think the first is the best... I always get annoyed looking at a timer... waiting for it to end.

**Comment by isidorn** [comment]
Maybe just do a 1s timeout. That will not hurt anybody and will give you that second you need to swtich windwos.

**Comment by joaomoreno** [comment]
Yeah and it will annoy you those times that you're not fast enough to get there and start recording. Sorry, I'll close this, since trim is exactly implemented to tackle this.
