### ISSUE TITLE
Not trivial to copy gif

### ISSUE THREAD

**Issue by isidorn** [joaomoreno/gifcap#12]
Once gif is recorder `copy image` copies the actual image not the gif.
In order to use the gif somewhere else I have to save it locally and then upload. Would be cool if I did not have to save it locally in order to use it.

**Comment by joaomoreno** [comment]
@isidorn Have you tried right click, copy image? We can add a copy button, for a single click experience.

**Comment by isidorn** [comment]
@joaomoreno yes I have tried that, and that copies the image not the gif.

**Comment by Tyriar** [comment]
I used it for the first time just now and found I don't need to copy it as downloading it will have it show up in your browsers downloads tray at the bottom which you can drag into github. I don't mind my downloads folder getting a little messy though.

**Comment by joaomoreno** [comment]
@isidorn This is so weird... I could swear this was working.

**Comment by joaomoreno** [comment]
https://htmldom.dev/download-a-file

**Comment by joaomoreno** [comment]
Clicking the image now downloads it. I've also added a download button to make it easier.

Browsers still don't let apps write images to the clipboard: https://web.dev/image-support-for-async-clipboard/ so closing this for now.
