### ISSUE TITLE
GIFs sometimes are too slow/fast

### ISSUE THREAD

**Issue by joaomoreno** [joaomoreno/gifcap#19]
I saw someone else mention that their gifs were not running at real time: https://news.ycombinator.com/item?id=22733912

@procload Is this true for you? The GIFs should always run at real time, it's an issue if they don't. Are they too fast? Are they too slow? The preview should actually already show whether it's too fast/slow.

**Comment by joaomoreno** [comment]
Theory: we capture using `setInterval` which can be always be offset and then assume it wasn't when rendering... let's simply capture all timestamps of each frame.

**Comment by joaomoreno** [comment]
cc @bvancea @Nils-2m

**Comment by joaomoreno** [comment]
First commit for a fix: https://github.com/joaomoreno/gifcap/commit/ba6d4a8d01c435d4a9419ca26cf9aa5d0a668604

Still need to fix `preview`.

**Comment by procload** [comment]
Correct, it was true for me. I couldn't get them to run in real time.

**Comment by joaomoreno** [comment]
@procload I just pushed something which might fix it, could you give it a try? https://gifcap.dev/ Make sure you get the latest changes by bypassing the browser cache (<kbd>Ctrl F5</kbd>) and ignore if the preview is still running _faster than it should_, proceed to render the GIF and let me know if the generated GIF runs at _real time_. Thanks!

**Comment by procload** [comment]
It's working much better, thanks for the fix! But it only works at normal speed on the initial window and not the windows in the background.

When I am typing in Chrome in the first, it is playing at the correct speed but when I switch apps and jump into VSCode, things go really fast.

**Comment by procload** [comment]
I emailed you an export of the gif since Github won't allow me to upload anything more than 10mb.

**Comment by joaomoreno** [comment]
> things go really fast

Do you mean _things go really slow_? That's at least what I observe from your GIF.

**Comment by joaomoreno** [comment]
So, it's known that browsers throttle background tabs. This is a problem for gifcap since recording always happens in the background, and it needs to run in a timely fashion in order to capture at a specific frame rate.

We were using `setInterval` for capturing the video frame. This gets heavily throttled by the browser, in a background tab. One could run with `setTimeout`, but that gets throttled as well. `requestAnimationFrame` would be another option, which also seems bad. Finally, I had the idea of creating a worker with the single purpose of pinging the main thread at exactly the frame rate... guess what, that actually works great. Wrote a small test suite to get some numbers on this: https://github.com/joaomoreno/gifcap/tree/7f0bf3f77aee44c06110123a87dd67989e4dc6a2/test. This is how that looks, when the tab is in the background:

Test | Average | Stdev | Count
-- | -- | -- | --
interval | 567 | 427.41 | 9
timeout | 567 | 420.16 | 9
animation frame | 112 | 16.55 | 4
worker | 101.46 | 11.32 | 50

We're supposed to get pinged every 100ms. The `worker` solution is only only which wasn't completely off the mark. It still has a stdev of ~10, but that's OK.

**Comment by procload** [comment]
Works great, thanks for the fix! I can finally ditch LICEcap now :)

**Comment by joaomoreno** [comment]
Thanks a lot for the quick update and for letting me know of the issue!
