### ISSUE TITLE
Better support for HiDPI

### ISSUE THREAD

**Issue by joaomoreno** [joaomoreno/gifcap#25]
GIFs are huge in pixel size, in HiDPI screens.

**Comment by joaomoreno** [comment]
Fixed by https://github.com/joaomoreno/gifcap/commit/748c16efa1c434f5e30129df1b1ba6388a602535

**Comment by Tyriar** [comment]
Seems a little blurry

<img width="651" alt="Screen Shot 2020-04-19 at 1 57 04 PM" src="https://user-images.githubusercontent.com/2193314/79699700-ebe18080-8245-11ea-9642-d054816363e7.png">

Does tweaking https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/imageSmoothingEnabled make it any better?

**Comment by joaomoreno** [comment]
That seems a LOT blurry. Can you show me a screenshot at 1x?

**Comment by Tyriar** [comment]
I zoomed in to see the pixels yes, but the text isn't very readable at its normal size was the point I was trying to make. See "File", "gif" etc, where letters are very blurred together.

**Comment by Tyriar** [comment]
Here's regular res:

<img width="220" alt="Screen Shot 2020-04-20 at 5 59 51 AM" src="https://user-images.githubusercontent.com/2193314/79754294-2988ec80-82cc-11ea-86c0-7532dea0e12b.png">

The fact I can see the pixels on a macbook display means something is wrong.

**Comment by joaomoreno** [comment]
This is indeed awful. Not really sure what we can do here, though. I'll revert this change.

**Comment by joaomoreno** [comment]
Alright, I got it. We shouldn't really scale this down, but simply use a better GIF encoder. Ran a small experiment and LiceCap is able to do a 6x file size reduction on a similar animation. We should benefit from frame similarity, a technique emloyed both from gifsicle and gifenc. Merging this into https://github.com/joaomoreno/gifcap/issues/6

**Comment by joaomoreno** [comment]
Reopening this! We should indeed scale the GIF down and just use a better scaling function than what the browser gives us. Luckily, https://github.com/joaomoreno/gifcap/issues/6 is in `master` and we can use gifsicle's resizing utils here.

**Comment by joaomoreno** [comment]
I was wrong again! Let's keep the original size. https://github.com/joaomoreno/gifcap/issues/6 will bring us everything we need.

**Comment by joaomoreno** [comment]
After discussing this again with @Tyriar, we figured out that integer `devicePixelRatio` values are actually valuable to scale down!

**Comment by connor4312** [comment]
One more fun edge case--in my setup my primary monitor is a 4K display with a 1.5 DPR, and I have a second (portrait-oriented) monitor that's standard 1080p. If I record the 4K display while the browser is on the 1080p monitor, the resulting gif is tiny:

![recording](https://user-images.githubusercontent.com/2230985/81094269-1b37f480-8eb8-11ea-84a2-c7f4276f7e91.gif)

**Comment by joaomoreno** [comment]
> One more fun edge case--in my setup my primary monitor is a 4K display with a 1.5 DPR, and I have a second (portrait-oriented) monitor that's standard 1080p. If I record the 4K display while the browser is on the 1080p monitor, the resulting gif is tiny:

Since gifcap isn't scaling everything yet... I say that's a bug on that browser for failure to adopt DPI change in the screensharing API.

**Comment by joaomoreno** [comment]
I believe fixed by https://github.com/joaomoreno/gifcap/pull/43
