### ISSUE TITLE
Download button does nothing

### ISSUE THREAD

**Issue by joaomoreno** [joaomoreno/gifcap#35]
cc @bpasero

**Comment by isidorn** [comment]
I also see this.
On top of this it is badly rendered
![Screenshot 2020-06-29 at 15 52 10](https://user-images.githubusercontent.com/1926584/86014346-80bfe180-ba20-11ea-9805-d08672c1c450.png)

**Comment by joaomoreno** [comment]
Yeah that seems to go away on reload. 🤷 Blame it on Chrome/Edge.

**Comment by joaomoreno** [comment]
Oh no! The icons were really deleted from the upstream service. Wtf!
