### ISSUE TITLE
Unable to record gif for VSCode insiders and stable if started with Admin privilages.

### ISSUE THREAD

**Issue by sanket-bhalerao** [joaomoreno/gifcap#36]
Hi,

I am trying to record a gif for the issue using gift cap.dev (firefox) for VSCode. when I click to start recording I get browser notification for permission, if I select VSCode from the dropdown the preview window shows just a black window.
![image](https://user-images.githubusercontent.com/9264813/89734400-9f7eb280-da79-11ea-9c6e-0f91ea3dc70d.png)
for other option, it shows a preview of sorts
if share entire screen option is selected then I can see VSCode window.

if the vscode is started with admin it does not allow recording (confirmed by starting in admin and normal priv levels).
if other apps started with admin privileges gifcap still able to capture them (confirmed with notepad, cmder, and windows command prompt applications)

if supporting admin priv app is out of scope, can there be a simple note added either to the site or the readme to avoid confusion?

**Comment by hediet** [comment]
This is more an issue of the browser than of gifcap. Gifcap can only use the browser API for accessing the screen.
Interesting that non-admin apps can screen-record some other admin apps...

Have you tried to start your browser as admin? Maybe then it can screen-record all other admin apps!

**Comment by joaomoreno** [comment]
Yeah closing this as designed. It's definitely a browser issue.
