### ISSUE TITLE
Persist changes when going back to edit rendered image

### ISSUE THREAD

**Issue by misolori** [joaomoreno/gifcap#45]
When I edit the video (crop and timeline) and then render, when you go back to re-edit my entire changes are reset. Would love it if it persisted these since sometimes i'll catch things when it's rendered that should be fixed (no cropped or looping correctly).

**Comment by joyceerhl** [comment]
I was recording a bunch of GIFs to illustrate a bug fix and found myself desperately wishing this feature existed, so I opened a PR for it https://github.com/joaomoreno/gifcap/pull/63
