### ISSUE TITLE
Dropdown Menu not Captured

### ISSUE THREAD

**Issue by bueti** [joaomoreno/gifcap#47]
Clicking on the dropdown menu and selecting an entry didn't get captured by gifcap:
![recording(1)](https://user-images.githubusercontent.com/383917/105169712-31f0ab00-5b1c-11eb-8b17-34d36ec726bf.gif)

Reproducible on other pages with drop down menus.

OS: macOS Catalina

Browser:
Name 	Firefox
Version 	84.0.2
Build ID 	20210105180113

**Comment by joaomoreno** [comment]
This has to do with how the browsers record, what you choose to record and how applications render. A dropdown menu in Firefox macOS gets rendered as a separate _window_. When you select the browser window to be recorded, other windows won't be recorded, and that includes the dropdown menu.

Workaround: select the entire screen and use the cropping mechanism to crop.

**Comment by bueti** [comment]
>A dropdown menu in Firefox macOS gets rendered as a separate window.

wow 🤯 Thanks for the explanation, and Hi as well 👋 :)
