### ISSUE TITLE
Recording Edge tab with status bar results in doubling of status bar

### ISSUE THREAD

**Issue by rzhao271** [joaomoreno/gifcap#48]
I wonder if it has to do with the notification that scrolls down the screen.

1. Start recording Edge tab with codespaces
2. Place the cursor on an editor and start typing
3. Press the stop button with the mouse
4. Bug: the preview shows up with a duplicated status bar

![recording (8)](https://user-images.githubusercontent.com/7199958/105772246-bd03e380-5f16-11eb-8dcf-f41de0149814.gif)

**Comment by joaomoreno** [comment]
@rzhao271 Can you reproduce with any other website in Edge?

**Comment by rzhao271** [comment]
Yep, reproduced with StackOverflow, which also has a status bar of sorts.

![recording (9)](https://user-images.githubusercontent.com/7199958/105876243-a52e6d00-5fb3-11eb-9014-b2670bcab411.gif)

**Comment by joaomoreno** [comment]
Can you repro with Chrome?

**Comment by rzhao271** [comment]
Yep, repro'd

![recording (10)](https://user-images.githubusercontent.com/7199958/106026619-e8a1dd80-607e-11eb-9f13-7a2033837310.gif)

**Comment by joaomoreno** [comment]
The issue here is that Chromium shows this weird bar and resizes the entire video stream while doing it:

![image](https://user-images.githubusercontent.com/22350/106139294-1a1fb500-6122-11eb-8338-365e378cb3d7.png)

That's pretty ugly.

**Comment by rzhao271** [comment]
Unable to repro now
