### ISSUE TITLE
Stop button flashes when hitting start on Android

### ISSUE THREAD

**Issue by Tyriar** [joaomoreno/gifcap#5]
Both in Chromium webview and Edge for Android.

**Comment by joaomoreno** [comment]
Already disabled this for mobile, not supported currently: https://github.com/joaomoreno/gifcap/commit/4c8b4beb97c6e157ac70193f55fe68bb64fda002#diff-7a9076d6d94e62c13d641aa71f19ae8eR109.

Thanks tho!

**Comment by Tyriar** [comment]
Yep, wasn't expecting it to work so it shouldn't present the start button.
