### ISSUE TITLE
REQUEST: Ability to create a new GIF after creating one GIF

### ISSUE THREAD

**Issue by rukshn** [joaomoreno/gifcap#51]
He, awesome application.

I would like to add this simple feature to the GIF cap app. That is once I completed creating a GIF it would be great if you can adda button or an option to create another GIF by clicking on it, rather than completely refreshing the page.

Keep up the good work

**Comment by joaomoreno** [comment]
> create another GIF by clicking on it,

I'm not sure what you mean by this? Once you finish creating a GIF, you can go ahead and just create another one.

**Comment by rukshn** [comment]
@joaomoreno Hi yes I realised that Discard button serves the purpose :) but it's not obvious at first sight what the discord button does
