### ISSUE TITLE
Context menu not always displayed in recording

### ISSUE THREAD

**Issue by nrayburn-tech** [joaomoreno/gifcap#56]
Reproduction steps
1. Start recording
2. Right click to display a context menu
3. Stop recording
4. See that the context menu is not displayed in the recording

This seems to depend on the browser and recording method selected.
- Safari doesn't have an option to pick a recording method, no context menu is ever shown.
- Brave doesn't show the context menu when recording a specific window or brave tab.  When recording the entire screen, the context menu is shown.

macOS 11.3.1
Safari 14.1
Brave 1.24.86 (Chromium 90.0.4430.212)

Reproduction video in Brave (Not made with gifcap)
![repro](https://user-images.githubusercontent.com/52075362/119286261-924a4300-bc09-11eb-8cda-f9fcbc165c54.gif)

Downloaded video
![recording](https://user-images.githubusercontent.com/52075362/119286273-9d9d6e80-bc09-11eb-83d4-981e7029f99e.gif)

**Comment by joaomoreno** [comment]
This is because the OS renders the context menu is a different window. The only way you can get this to work is to pick the entire desktop when the browser sharing picker comes up, instead of a single window.
