### ISSUE TITLE
 Improve rendering perf and output size

### ISSUE THREAD

**Issue by joaomoreno** [joaomoreno/gifcap#6]
Let's use [emscripten](https://emscripten.org/) to get ourselves a fast WASM GIF encoder, which can produce highly optimized GIFs by combining:

- [libimagequant](https://pngquant.org/lib/)
- [gifsicle](https://github.com/kohler/gifsicle)

**Comment by joaomoreno** [comment]
I noticed @kornelski has contributed giflossy to gifsicle and has also created gifski. @kornelski I wonder if you could let me know your thoughts on the differences between gifsicle and gifski?

**Comment by kornelski** [comment]
gifski is about making new GIFs with highest quality.

gifsicle is about making existing GIFs smaller.

**Comment by joaomoreno** [comment]
Got it, thanks for clearing that up! 👌

**Comment by Tyriar** [comment]
It's pretty hard to use this on a macbook and GitHub, the gif reaches 10mb very quickly on a high dpi screen which is the max size GitHub allows. I would normally use Kap for this where I would halve the resolution and set the FPS to 15. It would be nice if once these options are supported and are set, they're remembered for the browser.

**Comment by joaomoreno** [comment]
Alright, managed to get gifsicle working in wasm, exploration currently in `master`. Getting some great numbers for a very small example of 3 frames only:

- GifJS: 21Kb, 240ms
- WASM: 18Kb, 100ms

So, not only it produces a smaller output (I expect the difference to be more dramatic for a larger number of frames) but does it in under half the time.

Time to stitch it all out and get it into production!

**Comment by joaomoreno** [comment]
Actually, I'm ditching global palettes, which will have a slight impact on file size, but has a huge effect on performance: 19Kb, ~35ms

**Comment by joaomoreno** [comment]
Introducing workers actually brings the numbers all the way up due to lots of copying... but the end output size is smaller thanks to giflossy.

**Comment by joaomoreno** [comment]
Finally got this working very nicely and was able to apply some optimizations to reduce memory copying and parallelize this across multiple workers.

Here are some numbers of my machine running a [simple test case](https://github.com/joaomoreno/gifcap/tree/35cb7f80c1c0ec499feb23ffd4e5cb218a120e98/encoder/test) in which a video is rendered into a GIF using both gif.js and gifsicle in wasm:

  | render time (ms) | size (Kb)
-- | -- | --
gifjs | 1657 | 1046
gifsicle | 598 | 454

Both numbers are _lower is better_:

![image](https://user-images.githubusercontent.com/22350/80825909-9613bd80-8be1-11ea-9e9a-0063009138a6.png)

--- 

Test page:

![image](https://user-images.githubusercontent.com/22350/80826148-0589ad00-8be2-11ea-9202-d17b38c74cc9.png)

**Comment by joaomoreno** [comment]
After a couple more iterations on the approach, I am very satisfied with the results. Apart from using gifsicle to encode a gif (WASM is faster) and using its lossy feature (smaller files), I ended up making the following perf improvements:

- Frame quantization is parallelized across workers (faster)
- Equal sequential frames are dropped (faster, smaller GIFs)
- Only the boundary box of the differences between each frame is actually quantized and encoded (**much** smaller GIFs for static things like screen recordings)

The test sample doesn't get great numbers (I'm now at 767ms, 333Kb) since it's actually a video in which lots of pixels change

But check out this 111kb GIF 🔥 :

![image](https://user-images.githubusercontent.com/22350/80892249-e6197f80-8cc8-11ea-9864-e1a8ff12712b.png)

**Comment by joaomoreno** [comment]
This is now pushed: https://gifcap.dev/

@Tyriar @bpasero Can you give it a try, since I know GIF size was an issue for you? Please let me know how it goes, thanks! 🙏

**Comment by bpasero** [comment]
Works great enough that I will selfhost for a while, thanks. I still wish for being able to have a fast way to get a Gif into a GH issue, either by copying it to clipboard or automatically uploading it and then copying the link into clipboard.

**Comment by joaomoreno** [comment]
@bpasero No browser allows to copy images, much less GIFs, so it's just not possible for now: https://github.com/joaomoreno/gifcap/issues/12#issuecomment-623134700

We can investigate on uploading to websites.

**Comment by Tyriar** [comment]
It can't get much easier than it is right now; left click the download button and drag this into the GH comment box.

![image](https://user-images.githubusercontent.com/2193314/80952062-eb042f00-8dad-11ea-8f2e-b8d64735c38b.png)

**Comment by bpasero** [comment]
Does not seem to work from Edge to Chrome :(

**Comment by joaomoreno** [comment]
> Does not seem to work from Edge to Chrome :(

Why would you need this?

**Comment by bpasero** [comment]
I typically have my PWA apps in Edge and also have permissions setup for Edge (because I use it for Teams).
