### ISSUE TITLE
Does not record the color picker on a page

### ISSUE THREAD

**Issue by f2xiao** [joaomoreno/gifcap#68]
Found out that if there is a color picker input on the page, the recodring does not show the color select interface. Using chrome Version 97.0.4692.99 on windows.

**Comment by joaomoreno** [comment]
When you start recording, you can pick a window or the entire screen. If you pick a window, only that window will be recorded. Some applications render a color picker on a separate "window". I suggest to record the entire screen and then crop the result in gifcap.
