### ISSUE TITLE
gifcap fails to show app windows: DOMException: Permission denied

### ISSUE THREAD

**Issue by rebornix** [joaomoreno/gifcap#69]
From time to time I got `DOMException: Permission denied` and no window previews anymore

<img width="1547" alt="image" src="https://user-images.githubusercontent.com/876920/154116362-66ff0508-5f1c-4f6e-a373-2f7468a17aec.png">

**Comment by joaomoreno** [comment]
From @rebornix:

> I have a feeling it’s an Edge bug. To use gifcap we would need to enable screen recording for it and I don’t think we would disable it later on. It stopped working all of a sudden.
> However, disabling screen recording, quit Edge, enable it, open Edge again, then it works fine again. Restarting Edge only won’t fix the problem ;(
