### ISSUE TITLE
"Could not start video source"

### ISSUE THREAD

**Issue by roblourens** [joaomoreno/gifcap#73]
This is Edge on MacOS. I get the first error when selecting a screen to share. Then I tried a window, and it looked like it was recording, but I got the 'timestamp' error.
![image](https://user-images.githubusercontent.com/323878/168881374-afa063ff-2e8d-43fc-b2ac-e08278f2a433.png)

**Comment by roblourens** [comment]
Chrome worked

**Comment by joaomoreno** [comment]
🤷 Maybe browser permissions...

**Comment by roblourens** [comment]
Yeah, I dunno, it used to work. Lmk if you think there's anything useful I could debug

**Comment by joaomoreno** [comment]
Still repros after a restart?

**Comment by roblourens** [comment]
I already had this permission set

<img width="521" alt="image" src="https://user-images.githubusercontent.com/323878/169576988-160b2f7e-986e-46a8-a548-2ca9e50032a6.png">

I unchecked it, quit Edge, rechecked it, started Edge, and it worked 🤷 I also think I got a browser update last night.

**Comment by joaomoreno** [comment]
cc @isidorn

**Comment by isidorn** [comment]
Lol, unchecking chrome and checking it again worked for me as well.
@roblourens thanks for the workaround
