### ISSUE TITLE
Gifs made by gifcap.dev cannot be shared on Twitter

### ISSUE THREAD

**Issue by abidlabs** [joaomoreno/gifcap#74]
Hi there! First of all, thanks for making gifcap, I absolutely love and use the tool regularly!

However, I've noticed that recently (in the last couple of months), GIFs made by gifcap cannot be shared on Twitter. I'm not sure what the issue is, perhaps the format of the GIF is not right -- you can try this yourself. 

This makes it very hard since I have to convert the GIF to a video before I can post it.

**Comment by abidlabs** [comment]
Here's an example I just tried: 

<img width="470" alt="image" src="https://user-images.githubusercontent.com/1778297/171432626-7d0de8ec-f418-457b-8c24-d70164fc64da.png">

All Twitter says is, "Something went wrong, but don’t fret — let’s give it another shot."

But even if I give it an other shot, I still get the same error. For reference, I am running gifcap.dev on a Windows machine using the Edge browser.

**Comment by abidlabs** [comment]
I can't make too much sense of what I'm seeing in the devtools unfortunately

**Comment by abidlabs** [comment]
Yup just tried with a fresh install of Chrome and the same problem happens. Also asked one of my friends who had the same issue as well.

Here is the GIF if you'd like to try it:

![Recording 2022-06-03 at 16 23 58](https://user-images.githubusercontent.com/1778297/171966297-2d8f4b08-0bcb-4bbe-8513-0dace1f2804b.gif)

**Comment by joaomoreno** [comment]
Twitter says:

> BadRequest: Image dimensions must be >= 4x4 and <= 2048x2048 (324)

![image](https://user-images.githubusercontent.com/22350/172305220-fdeb9c8c-6fc8-4672-b0cc-ad6dc7978146.png)

**Comment by abidlabs** [comment]
Ah okay may be it has to do with my screen dimensions then?

**Comment by joaomoreno** [comment]
After recording, simply click and drag in gifcap's view and you'll be able to crop the GIF.
