### ISSUE TITLE
Click render, nothing happens

### ISSUE THREAD

**Issue by jnfielding** [joaomoreno/gifcap#75]
Had this issue for several months, may be on my side as i haven't tested on another device yet.

Recording works fine, after render is clicked, the loading bar does not progress and it just halts at the start.

Chrome on Macbook

**Comment by joaomoreno** [comment]
Any error in devtools?

**Comment by jnfielding** [comment]
Nothing i can see

I tested it again and left it for a long time (2+minutes) while I was
looking at devtools and it worked.

Could be my extensions interfering

Feel free to close the issue, thanks
