### ISSUE TITLE
What backend can we use to self host this

### ISSUE THREAD

**Issue by hellrazorx64** [joaomoreno/gifcap#79]
I tried putting the directory to apache but index page only shows the .html all white?

(what was meant in the op)

**Comment by joaomoreno** [comment]
Sorry but I won't give you support to do this.

**Comment by hellrazorx64** [comment]
I didn't mean to walk me through the whole process but simply a word... like what webserver you used, or engine etc...

But also, no is also a valid answer. 

Wish you luck in your projects

**Comment by joaomoreno** [comment]
gifcap doesn't require any server: it's a 100% client side app. All you need is a basic web server which serves static files.

**Comment by hellrazorx64** [comment]
> gifcap doesn't require any server: it's a 100% client side app. All you need is a basic web server which serves static files.

Thanks, now I know it's common knowledge and nothing tricky.
