### ISSUE TITLE
Is a docker container possible in the future to self host this?

### ISSUE THREAD

**Issue by krabs-github** [joaomoreno/gifcap#80]
Is a docker container possible in the future to self host this?

**Comment by joaomoreno** [comment]
It's all static HTML/JavaScript/CSS. No need for a docker container.

**Comment by krabs-github** [comment]
In the repository, there is no main.js. There are pieces missing preventing it running.

**Comment by joaomoreno** [comment]
Look into the [gh action](https://github.com/joaomoreno/gifcap/blob/main/.github/workflows/build.yml) to see how this is built and deployed.
