### ISSUE TITLE
Cannot share screen with gifcap

### ISSUE THREAD

**Issue by luetage** [joaomoreno/gifcap#87]
Environment:
Vivaldi 5.7.2912.12 / Chrome 110.0.5481.38
Fedora 37 / Gnome 43.2

Reproduce:
* Visit https://gifcap.dev
* Click “Start Recording”.
* In the ensuing dialog we can choose between entire screen, window, or tab. Choose »screen« and click »share.«
* Record a few seconds, then stop.

Expected result:
The entire screen should be recorded.

Actual Result:
Recording only shows the mouse cursor on a black
background.

Notes:
This happens both on Vivaldi and regular Chrome. Repeating the steps with Firefox gives the option to use operating system settings, which triggers a screen share system dialog, where I can select my monitor and start recording. An icon is visible in the top panel, indicating the screen is being shared. I’m not sure whether this is an issue with gifcap or Chrome browsers on Linux.

**Comment by joaomoreno** [comment]
If you use Zoom/Teams on that browser setup and share your screen, do people see the screen, or the same bug reproduces?

**Comment by luetage** [comment]
Thanks for taking a look. Strangely, this is suddenly resolved. I first reported the problem to Vivaldi over a year ago and recently someone could reproduce, that’s why I asked for support here. My best guess is a recent Chromium update fixed it.
