### ISSUE TITLE
need for downsize the output gif 

### ISSUE THREAD

**Issue by zzha0199** [joaomoreno/gifcap#91]
I'm not sure if it is due to my high-screen resolution, but the output gif file is very large, 1 second in 18.75% of the selected area of a 15.6-inch screen would have a size of 3.7MB. When I tried to use the other gif downsizing web, it could only generate a 3.7MB to 3.2MB. 
Thus, I'm wondering if it is possible to add a function for choosing the output resolution (downsizing) of the gif when rendering and outputing. Thank you.

**Comment by joaomoreno** [comment]
Scaling isn't something gifcap supports, you can do that using other tools. But gifcap does support cropping, simply click and drag from the preview view.
