### ISSUE TITLE
GifCap doesn't capture mouse click highlighting (PowerToys feature)

### ISSUE THREAD

**Issue by exanrauzer** [joaomoreno/gifcap#92]
The GifCap lacks the ability to capture mouse click highlighting, a functionality present in PowerToys. When recording a GIF using GifCap, the mouse clicks are not visually highlighted on the screen, which can be a useful feature for instructional or demonstration purposes.

Expected Behavior:
GifCap should include the functionality to visually highlight mouse clicks during screen recording. This feature aids in emphasizing mouse interactions and helps create more informative and illustrative GIFs.

Windows 10
Chrome

**Comment by joaomoreno** [comment]
This is not supported via the screen sharing Web APIs, so impossible to achieve for the time being,

**Comment by exanrauzer** [comment]
Thank you for the answer!

Do you think that this may be changed on PowerToys side?
