### ISSUE TITLE
Does not work is Chrome is not turned on

### ISSUE THREAD

**Issue by isidorn** [joaomoreno/gifcap#93]
1. Close Chrome
2. Start GifCap. GifCap automatically starts Chrome and auto closes 🐛 

Ideally GifCap could work if I have just Edge running.
If that is not possible, could it auto launch Chrome and not close?

**Comment by joaomoreno** [comment]
Did you install gifcap as a PWA? On which browser?

This feels just like a PWA issue with Chrome.

**Comment by isidorn** [comment]
Got it! Yes I was using it as a PWA. So I should just start using it as a PWA for Edge. Thanks and sorry for the noise.
